# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  igtswashbuckleodatasamplewebapi:
    image: igtswashbuckleodatasamplewebapi
    build:
      context: .
      dockerfile: src/SampleWebApi/Dockerfile
    ports:
      - 80
      - 5000
      - 5001
